# Generated by Django 4.2.23 on 2025-08-29 17:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hotels', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField(verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complement')),
                ('is_available', models.BooleanField(default=True, verbose_name='is_available')),
                ('hotel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_hotel_set', to='hotels.hotel', verbose_name='hotel')),
            ],
        ),
    ]
