# Generated by Django 4.2.23 on 2025-08-28 20:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='check_in')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='check_out')),
                ('status', models.CharField(blank=True, max_length=20, null=True, verbose_name='status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_reservation_set', to=settings.AUTH_USER_MODEL, verbose_name='customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_reservation_set', to='rooms.room', verbose_name='room')),
            ],
        ),
    ]
