# Generated by Django 4.2.23 on 2025-08-29 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rooms', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in', models.DateField(blank=True, null=True, verbose_name='check_in')),
                ('check_out', models.DateField(blank=True, null=True, verbose_name='check_out')),
                ('booking_status', models.CharField(blank=True, default='Pending', max_length=20, null=True, verbose_name='booking_status')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_customer_set', to='customers.customer', verbose_name='customer')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reservation_room_set', to='rooms.room', verbose_name='room')),
            ],
        ),
    ]
