# Generated by Django 4.2.23 on 2025-08-29 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='reservation_code',
            field=models.CharField(blank=True, default='', max_length=20, null=True, verbose_name='reservation_code'),
        ),
    ]
