# Generated by Django 4.2.23 on 2025-08-29 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hotel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('email', models.EmailField(max_length=254, verbose_name='email')),
                ('phone', models.CharField(max_length=255, verbose_name='phone')),
                ('street', models.CharField(max_length=255, verbose_name='street')),
                ('number', models.CharField(max_length=255, verbose_name='number')),
                ('complement', models.CharField(blank=True, max_length=255, null=True, verbose_name='complement')),
                ('city', models.CharField(max_length=255, verbose_name='city')),
                ('state', models.CharField(max_length=255, verbose_name='state')),
                ('zip_code', models.CharField(max_length=255, verbose_name='zip_code')),
                ('website', models.URLField(blank=True, null=True, verbose_name='website')),
            ],
            options={
                'verbose_name': 'Hotel',
                'verbose_name_plural': 'Hotels',
            },
        ),
    ]
